# Project information
site_name: DeepLIIF
#site_url: https://github.com/pages/nadeemlab/DeepLIIF/

# Repo
repo_name: DeepLIIF
repo_url: https://github.com/nadeemlab/DeepLIIF
edit_uri: edit/main/docs

# Navigation
nav:
  - Home: README.md
  - Installation: installation/README.md
  - Training: training/README.md
  - Testing: testing/README.md
  - Deployment: deployment/README.md
  - ImageJ Plugin: ImageJ/README.md
  - Cloud Deployment: cloud/README.md

# Theme
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: white
    accent: grey
  logo: images/DeepLIIF_logo.png